se mejoró el título
fabianlucena/rf-locale pull request #3
Opened 2024-10-07 20:04 UTC by CandeBarboza

2024-10-07 20:06 UTC, fabianlucena requested changes

2024-10-07 20:06 UTC, fabianlucena commented on public_html/style.css
> +    text-align: center;
Me parece que el título queda mejor alineado a la izquierda.

2024-10-07 21:20 UTC, CandeBarboza commented on public_html/style.css
> +    text-align: center;
Ya está el título alineado a la izquierda.

2024-10-08 19:10 UTC, fabianlucena approved these changes

2024-10-08 19:11 UTC, merged